// Make sure that binding definition files are always set to NOT use pre-compiled headers and conformance mode (/permissive) otherwise everything will be on fire!

#include "LuaBindingRegisterDefinitions.h"

#include "SDL_scancode.h"
#include "SDL_keycode.h"
#include "SDL_gamecontroller.h"

namespace RTE {

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	LuaBindingRegisterFunctionDefinitionForType(InputLuaBindings, InputDevice) {
		return luabind::class_<input_device>("InputDevice")

		.enum_("InputDevice")[
			luabind::value("DEVICE_KEYB_ONLY", InputDevice::DEVICE_KEYB_ONLY),
			luabind::value("DEVICE_MOUSE_KEYB", InputDevice::DEVICE_MOUSE_KEYB),
			luabind::value("DEVICE_GAMEPAD_1", InputDevice::DEVICE_GAMEPAD_1),
			luabind::value("DEVICE_GAMEPAD_2", InputDevice::DEVICE_GAMEPAD_2),
			luabind::value("DEVICE_GAMEPAD_3", InputDevice::DEVICE_GAMEPAD_3),
			luabind::value("DEVICE_GAMEPAD_4", InputDevice::DEVICE_GAMEPAD_4),
			luabind::value("DEVICE_COUNT", InputDevice::DEVICE_COUNT)
		];
	}

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	LuaBindingRegisterFunctionDefinitionForType(InputLuaBindings, InputElements) {
		return luabind::class_<input_elements>("InputElements")

		.enum_("InputElements")[
			luabind::value("INPUT_L_UP", InputElements::INPUT_L_UP),
			luabind::value("INPUT_L_DOWN", InputElements::INPUT_L_DOWN),
			luabind::value("INPUT_L_LEFT", InputElements::INPUT_L_LEFT),
			luabind::value("INPUT_L_RIGHT", InputElements::INPUT_L_RIGHT),
			luabind::value("INPUT_R_UP", InputElements::INPUT_R_UP),
			luabind::value("INPUT_R_DOWN", InputElements::INPUT_R_DOWN),
			luabind::value("INPUT_R_LEFT", InputElements::INPUT_R_LEFT),
			luabind::value("INPUT_R_RIGHT", InputElements::INPUT_R_RIGHT),
			luabind::value("INPUT_FIRE", InputElements::INPUT_FIRE),
			luabind::value("INPUT_AIM", InputElements::INPUT_AIM),
			luabind::value("INPUT_AIM_UP", InputElements::INPUT_AIM_UP),
			luabind::value("INPUT_AIM_DOWN", InputElements::INPUT_AIM_DOWN),
			luabind::value("INPUT_AIM_LEFT", InputElements::INPUT_AIM_LEFT),
			luabind::value("INPUT_AIM_RIGHT", InputElements::INPUT_AIM_RIGHT),
			luabind::value("INPUT_PIEMENU", InputElements::INPUT_PIEMENU),
			luabind::value("INPUT_JUMP", InputElements::INPUT_JUMP),
			luabind::value("INPUT_CROUCH", InputElements::INPUT_CROUCH),
			luabind::value("INPUT_NEXT", InputElements::INPUT_NEXT),
			luabind::value("INPUT_PREV", InputElements::INPUT_PREV),
			luabind::value("INPUT_START", InputElements::INPUT_START),
			luabind::value("INPUT_BACK", InputElements::INPUT_BACK),
			luabind::value("INPUT_COUNT", InputElements::INPUT_COUNT)
		];
	}

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	LuaBindingRegisterFunctionDefinitionForType(InputLuaBindings, MouseButtons) {
		return luabind::class_<mouse_buttons>("MouseButtons")

		.enum_("MouseButtons")[
			luabind::value("MOUSE_NONE", MouseButtons::MOUSE_NONE),
			luabind::value("MOUSE_LEFT", MouseButtons::MOUSE_LEFT),
			luabind::value("MOUSE_RIGHT", MouseButtons::MOUSE_RIGHT),
			luabind::value("MOUSE_MIDDLE", MouseButtons::MOUSE_MIDDLE),
			luabind::value("MAX_MOUSE_BUTTONS", MouseButtons::MAX_MOUSE_BUTTONS)
		];
	}

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	LuaBindingRegisterFunctionDefinitionForType(InputLuaBindings, JoyButtons) {
		return luabind::class_<joy_buttons>("JoyButtons")

		.enum_("JoyButtons")[
			luabind::value("JOY_NONE", JoyButtons::JOY_NONE),
			luabind::value("JOY_1", JoyButtons::JOY_1),
			luabind::value("JOY_2", JoyButtons::JOY_2),
			luabind::value("JOY_3", JoyButtons::JOY_3),
			luabind::value("JOY_4", JoyButtons::JOY_4),
			luabind::value("JOY_5", JoyButtons::JOY_5),
			luabind::value("JOY_6", JoyButtons::JOY_6),
			luabind::value("JOY_7", JoyButtons::JOY_7),
			luabind::value("JOY_8", JoyButtons::JOY_8),
			luabind::value("JOY_9", JoyButtons::JOY_9),
			luabind::value("JOY_10", JoyButtons::JOY_10),
			luabind::value("JOY_11", JoyButtons::JOY_11),
			luabind::value("JOY_12", JoyButtons::JOY_12),
			luabind::value("MAX_JOY_BUTTONS", JoyButtons::MAX_JOY_BUTTONS)
		];
	}

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	LuaBindingRegisterFunctionDefinitionForType(InputLuaBindings, JoyDirections) {
		return luabind::class_<joy_directions>("JoyDirections")

		.enum_("JoyDirections")[
			luabind::value("JOYDIR_ONE", JoyDirections::JOYDIR_ONE),
			luabind::value("JOYDIR_TWO", JoyDirections::JOYDIR_TWO)
		];
	}

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	LuaBindingRegisterFunctionDefinitionForType(InputLuaBindings, SDL_Keycode) {
		return luabind::class_<key_codes>("Key")

		// Make sure to update https://github.com/cortex-command-community/Cortex-Command-Community-Project-Source/wiki/SDL-Keycode-and-Scancode-enum-values-in-Lua#key-codes if any changes are made.
		.enum_("Key")[
			luabind::value("UNKNOWN", SDLK_UNKNOWN),
			luabind::value("RETURN", SDLK_RETURN),
			luabind::value("ESCAPE", SDLK_ESCAPE),
			luabind::value("BACKSPACE", SDLK_BACKSPACE),
			luabind::value("TAB", SDLK_TAB),
			luabind::value("SPACE", SDLK_SPACE),
			luabind::value("EXCLAIM", SDLK_EXCLAIM),
			luabind::value("QUOTEDBL", SDLK_QUOTEDBL),
			luabind::value("HASH", SDLK_HASH),
			luabind::value("PERCENT", SDLK_PERCENT),
			luabind::value("DOLLAR", SDLK_DOLLAR),
			luabind::value("AMPERSAND", SDLK_AMPERSAND),
			luabind::value("QUOTE", SDLK_QUOTE),
			luabind::value("LEFTPAREN", SDLK_LEFTPAREN),
			luabind::value("RIGHTPAREN", SDLK_RIGHTPAREN),
			luabind::value("ASTERISK", SDLK_ASTERISK),
			luabind::value("PLUS", SDLK_PLUS),
			luabind::value("COMMA", SDLK_COMMA),
			luabind::value("MINUS", SDLK_MINUS),
			luabind::value("PERIOD", SDLK_PERIOD),
			luabind::value("SLASH", SDLK_SLASH),
			luabind::value("0", SDLK_0),
			luabind::value("1", SDLK_1),
			luabind::value("2", SDLK_2),
			luabind::value("3", SDLK_3),
			luabind::value("4", SDLK_4),
			luabind::value("5", SDLK_5),
			luabind::value("6", SDLK_6),
			luabind::value("7", SDLK_7),
			luabind::value("8", SDLK_8),
			luabind::value("9", SDLK_9),
			luabind::value("COLON", SDLK_COLON),
			luabind::value("SEMICOLON", SDLK_SEMICOLON),
			luabind::value("LESS", SDLK_LESS),
			luabind::value("EQUALS", SDLK_EQUALS),
			luabind::value("GREATER", SDLK_GREATER),
			luabind::value("QUESTION", SDLK_QUESTION),
			luabind::value("AT", SDLK_AT),
			luabind::value("LEFTBRACKET", SDLK_LEFTBRACKET),
			luabind::value("BACKSLASH", SDLK_BACKSLASH),
			luabind::value("RIGHTBRACKET", SDLK_RIGHTBRACKET),
			luabind::value("CARET", SDLK_CARET),
			luabind::value("UNDERSCORE", SDLK_UNDERSCORE),
			luabind::value("BACKQUOTE", SDLK_BACKQUOTE),
			luabind::value("a", SDLK_a),
			luabind::value("b", SDLK_b),
			luabind::value("c", SDLK_c),
			luabind::value("d", SDLK_d),
			luabind::value("e", SDLK_e),
			luabind::value("f", SDLK_f),
			luabind::value("g", SDLK_g),
			luabind::value("h", SDLK_h),
			luabind::value("i", SDLK_i),
			luabind::value("j", SDLK_j),
			luabind::value("k", SDLK_k),
			luabind::value("l", SDLK_l),
			luabind::value("m", SDLK_m),
			luabind::value("n", SDLK_n),
			luabind::value("o", SDLK_o),
			luabind::value("p", SDLK_p),
			luabind::value("q", SDLK_q),
			luabind::value("r", SDLK_r),
			luabind::value("s", SDLK_s),
			luabind::value("t", SDLK_t),
			luabind::value("u", SDLK_u),
			luabind::value("v", SDLK_v),
			luabind::value("w", SDLK_w),
			luabind::value("x", SDLK_x),
			luabind::value("y", SDLK_y),
			luabind::value("z", SDLK_z),
			luabind::value("CAPSLOCK", SDLK_CAPSLOCK),
			luabind::value("F1", SDLK_F1),
			luabind::value("F2", SDLK_F2),
			luabind::value("F3", SDLK_F3),
			luabind::value("F4", SDLK_F4),
			luabind::value("F5", SDLK_F5),
			luabind::value("F6", SDLK_F6),
			luabind::value("F7", SDLK_F7),
			luabind::value("F8", SDLK_F8),
			luabind::value("F9", SDLK_F9),
			luabind::value("F10", SDLK_F10),
			luabind::value("F11", SDLK_F11),
			luabind::value("F12", SDLK_F12),
			luabind::value("PRINTSCREEN", SDLK_PRINTSCREEN),
			luabind::value("SCROLLLOCK", SDLK_SCROLLLOCK),
			luabind::value("PAUSE", SDLK_PAUSE),
			luabind::value("INSERT", SDLK_INSERT),
			luabind::value("HOME", SDLK_HOME),
			luabind::value("PAGEUP", SDLK_PAGEUP),
			luabind::value("DELETE", SDLK_DELETE),
			luabind::value("END", SDLK_END),
			luabind::value("PAGEDOWN", SDLK_PAGEDOWN),
			luabind::value("RIGHT", SDLK_RIGHT),
			luabind::value("LEFT", SDLK_LEFT),
			luabind::value("DOWN", SDLK_DOWN),
			luabind::value("UP", SDLK_UP),
			luabind::value("NUMLOCKCLEAR", SDLK_NUMLOCKCLEAR),
			luabind::value("KP_DIVIDE", SDLK_KP_DIVIDE),
			luabind::value("KP_MULTIPLY", SDLK_KP_MULTIPLY),
			luabind::value("KP_MINUS", SDLK_KP_MINUS),
			luabind::value("KP_PLUS", SDLK_KP_PLUS),
			luabind::value("KP_ENTER", SDLK_KP_ENTER),
			luabind::value("KP_1", SDLK_KP_1),
			luabind::value("KP_2", SDLK_KP_2),
			luabind::value("KP_3", SDLK_KP_3),
			luabind::value("KP_4", SDLK_KP_4),
			luabind::value("KP_5", SDLK_KP_5),
			luabind::value("KP_6", SDLK_KP_6),
			luabind::value("KP_7", SDLK_KP_7),
			luabind::value("KP_8", SDLK_KP_8),
			luabind::value("KP_9", SDLK_KP_9),
			luabind::value("KP_0", SDLK_KP_0),
			luabind::value("KP_PERIOD", SDLK_KP_PERIOD),
			luabind::value("APPLICATION", SDLK_APPLICATION),
			luabind::value("POWER", SDLK_POWER),
			luabind::value("KP_EQUALS", SDLK_KP_EQUALS),
			luabind::value("F13", SDLK_F13),
			luabind::value("F14", SDLK_F14),
			luabind::value("F15", SDLK_F15),
			luabind::value("F16", SDLK_F16),
			luabind::value("F17", SDLK_F17),
			luabind::value("F18", SDLK_F18),
			luabind::value("F19", SDLK_F19),
			luabind::value("F20", SDLK_F20),
			luabind::value("F21", SDLK_F21),
			luabind::value("F22", SDLK_F22),
			luabind::value("F23", SDLK_F23),
			luabind::value("F24", SDLK_F24),
			luabind::value("EXECUTE", SDLK_EXECUTE),
			luabind::value("HELP", SDLK_HELP),
			luabind::value("MENU", SDLK_MENU),
			luabind::value("SELECT", SDLK_SELECT),
			luabind::value("STOP", SDLK_STOP),
			luabind::value("AGAIN", SDLK_AGAIN),
			luabind::value("UNDO", SDLK_UNDO),
			luabind::value("CUT", SDLK_CUT),
			luabind::value("COPY", SDLK_COPY),
			luabind::value("PASTE", SDLK_PASTE),
			luabind::value("FIND", SDLK_FIND),
			luabind::value("MUTE", SDLK_MUTE),
			luabind::value("VOLUMEUP", SDLK_VOLUMEUP),
			luabind::value("VOLUMEDOWN", SDLK_VOLUMEDOWN),
			luabind::value("KP_COMMA", SDLK_KP_COMMA),
			luabind::value("KP_EQUALSAS400", SDLK_KP_EQUALSAS400),
			luabind::value("ALTERASE", SDLK_ALTERASE),
			luabind::value("SYSREQ", SDLK_SYSREQ),
			luabind::value("CANCEL", SDLK_CANCEL),
			luabind::value("CLEAR", SDLK_CLEAR),
			luabind::value("PRIOR", SDLK_PRIOR),
			luabind::value("RETURN2", SDLK_RETURN2),
			luabind::value("SEPARATOR", SDLK_SEPARATOR),
			luabind::value("OUT", SDLK_OUT),
			luabind::value("OPER", SDLK_OPER),
			luabind::value("CLEARAGAIN", SDLK_CLEARAGAIN),
			luabind::value("CRSEL", SDLK_CRSEL),
			luabind::value("EXSEL", SDLK_EXSEL),
			luabind::value("KP_00", SDLK_KP_00),
			luabind::value("KP_000", SDLK_KP_000),
			luabind::value("THOUSANDSSEPARATOR", SDLK_THOUSANDSSEPARATOR),
			luabind::value("DECIMALSEPARATOR", SDLK_DECIMALSEPARATOR),
			luabind::value("CURRENCYUNIT", SDLK_CURRENCYUNIT),
			luabind::value("CURRENCYSUBUNIT", SDLK_CURRENCYSUBUNIT),
			luabind::value("KP_LEFTPAREN", SDLK_KP_LEFTPAREN),
			luabind::value("KP_RIGHTPAREN", SDLK_KP_RIGHTPAREN),
			luabind::value("KP_LEFTBRACE", SDLK_KP_LEFTBRACE),
			luabind::value("KP_RIGHTBRACE", SDLK_KP_RIGHTBRACE),
			luabind::value("KP_TAB", SDLK_KP_TAB),
			luabind::value("KP_BACKSPACE", SDLK_KP_BACKSPACE),
			luabind::value("KP_A", SDLK_KP_A),
			luabind::value("KP_B", SDLK_KP_B),
			luabind::value("KP_C", SDLK_KP_C),
			luabind::value("KP_D", SDLK_KP_D),
			luabind::value("KP_E", SDLK_KP_E),
			luabind::value("KP_F", SDLK_KP_F),
			luabind::value("KP_XOR", SDLK_KP_XOR),
			luabind::value("KP_POWER", SDLK_KP_POWER),
			luabind::value("KP_PERCENT", SDLK_KP_PERCENT),
			luabind::value("KP_LESS", SDLK_KP_LESS),
			luabind::value("KP_GREATER", SDLK_KP_GREATER),
			luabind::value("KP_AMPERSAND", SDLK_KP_AMPERSAND),
			luabind::value("KP_DBLAMPERSAND", SDLK_KP_DBLAMPERSAND),
			luabind::value("KP_VERTICALBAR", SDLK_KP_VERTICALBAR),
			luabind::value("KP_DBLVERTICALBAR", SDLK_KP_DBLVERTICALBAR),
			luabind::value("KP_COLON", SDLK_KP_COLON),
			luabind::value("KP_HASH", SDLK_KP_HASH),
			luabind::value("KP_SPACE", SDLK_KP_SPACE),
			luabind::value("KP_AT", SDLK_KP_AT),
			luabind::value("KP_EXCLAM", SDLK_KP_EXCLAM),
			luabind::value("KP_MEMSTORE", SDLK_KP_MEMSTORE),
			luabind::value("KP_MEMRECALL", SDLK_KP_MEMRECALL),
			luabind::value("KP_MEMCLEAR", SDLK_KP_MEMCLEAR),
			luabind::value("KP_MEMADD", SDLK_KP_MEMADD),
			luabind::value("KP_MEMSUBTRACT", SDLK_KP_MEMSUBTRACT),
			luabind::value("KP_MEMMULTIPLY", SDLK_KP_MEMMULTIPLY),
			luabind::value("KP_MEMDIVIDE", SDLK_KP_MEMDIVIDE),
			luabind::value("KP_PLUSMINUS", SDLK_KP_PLUSMINUS),
			luabind::value("KP_CLEAR", SDLK_KP_CLEAR),
			luabind::value("KP_CLEARENTRY", SDLK_KP_CLEARENTRY),
			luabind::value("KP_BINARY", SDLK_KP_BINARY),
			luabind::value("KP_OCTAL", SDLK_KP_OCTAL),
			luabind::value("KP_DECIMAL", SDLK_KP_DECIMAL),
			luabind::value("KP_HEXADECIMAL", SDLK_KP_HEXADECIMAL),
			luabind::value("LCTRL", SDLK_LCTRL),
			luabind::value("LSHIFT", SDLK_LSHIFT),
			luabind::value("LALT", SDLK_LALT),
			luabind::value("LGUI", SDLK_LGUI),
			luabind::value("RCTRL", SDLK_RCTRL),
			luabind::value("RSHIFT", SDLK_RSHIFT),
			luabind::value("RALT", SDLK_RALT),
			luabind::value("RGUI", SDLK_RGUI),
			luabind::value("MODE", SDLK_MODE),
			luabind::value("AUDIONEXT", SDLK_AUDIONEXT),
			luabind::value("AUDIOPREV", SDLK_AUDIOPREV),
			luabind::value("AUDIOSTOP", SDLK_AUDIOSTOP),
			luabind::value("AUDIOPLAY", SDLK_AUDIOPLAY),
			luabind::value("AUDIOMUTE", SDLK_AUDIOMUTE),
			luabind::value("MEDIASELECT", SDLK_MEDIASELECT),
			luabind::value("WWW", SDLK_WWW),
			luabind::value("MAIL", SDLK_MAIL),
			luabind::value("CALCULATOR", SDLK_CALCULATOR),
			luabind::value("COMPUTER", SDLK_COMPUTER),
			luabind::value("AC_SEARCH", SDLK_AC_SEARCH),
			luabind::value("AC_HOME", SDLK_AC_HOME),
			luabind::value("AC_BACK", SDLK_AC_BACK),
			luabind::value("AC_FORWARD", SDLK_AC_FORWARD),
			luabind::value("AC_STOP", SDLK_AC_STOP),
			luabind::value("AC_REFRESH", SDLK_AC_REFRESH),
			luabind::value("AC_BOOKMARKS", SDLK_AC_BOOKMARKS),
			luabind::value("BRIGHTNESSDOWN", SDLK_BRIGHTNESSDOWN),
			luabind::value("BRIGHTNESSUP", SDLK_BRIGHTNESSUP),
			luabind::value("DISPLAYSWITCH", SDLK_DISPLAYSWITCH),
			luabind::value("KBDILLUMTOGGLE", SDLK_KBDILLUMTOGGLE),
			luabind::value("KBDILLUMDOWN", SDLK_KBDILLUMDOWN),
			luabind::value("KBDILLUMUP", SDLK_KBDILLUMUP),
			luabind::value("EJECT", SDLK_EJECT),
			luabind::value("SLEEP", SDLK_SLEEP)
		];
	}

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	LuaBindingRegisterFunctionDefinitionForType(InputLuaBindings, SDL_Scancode) {
		return luabind::class_<scan_codes>("Scancode")

		// Make sure to update https://github.com/cortex-command-community/Cortex-Command-Community-Project-Source/wiki/SDL-Keycode-and-Scancode-enum-values-in-Lua#scan-codes if any changes are made.
		.enum_("Scancode")[
			luabind::value("UNKNOWN", SDL_SCANCODE_UNKNOWN),
			luabind::value("A", SDL_SCANCODE_A),
			luabind::value("B", SDL_SCANCODE_B),
			luabind::value("C", SDL_SCANCODE_C),
			luabind::value("D", SDL_SCANCODE_D),
			luabind::value("E", SDL_SCANCODE_E),
			luabind::value("F", SDL_SCANCODE_F),
			luabind::value("G", SDL_SCANCODE_G),
			luabind::value("H", SDL_SCANCODE_H),
			luabind::value("I", SDL_SCANCODE_I),
			luabind::value("J", SDL_SCANCODE_J),
			luabind::value("K", SDL_SCANCODE_K),
			luabind::value("L", SDL_SCANCODE_L),
			luabind::value("M", SDL_SCANCODE_M),
			luabind::value("N", SDL_SCANCODE_N),
			luabind::value("O", SDL_SCANCODE_O),
			luabind::value("P", SDL_SCANCODE_P),
			luabind::value("Q", SDL_SCANCODE_Q),
			luabind::value("R", SDL_SCANCODE_R),
			luabind::value("S", SDL_SCANCODE_S),
			luabind::value("T", SDL_SCANCODE_T),
			luabind::value("U", SDL_SCANCODE_U),
			luabind::value("V", SDL_SCANCODE_V),
			luabind::value("W", SDL_SCANCODE_W),
			luabind::value("X", SDL_SCANCODE_X),
			luabind::value("Y", SDL_SCANCODE_Y),
			luabind::value("Z", SDL_SCANCODE_Z),
			luabind::value("1", SDL_SCANCODE_1),
			luabind::value("2", SDL_SCANCODE_2),
			luabind::value("3", SDL_SCANCODE_3),
			luabind::value("4", SDL_SCANCODE_4),
			luabind::value("5", SDL_SCANCODE_5),
			luabind::value("6", SDL_SCANCODE_6),
			luabind::value("7", SDL_SCANCODE_7),
			luabind::value("8", SDL_SCANCODE_8),
			luabind::value("9", SDL_SCANCODE_9),
			luabind::value("0", SDL_SCANCODE_0),
			luabind::value("RETURN", SDL_SCANCODE_RETURN),
			luabind::value("ESCAPE", SDL_SCANCODE_ESCAPE),
			luabind::value("BACKSPACE", SDL_SCANCODE_BACKSPACE),
			luabind::value("TAB", SDL_SCANCODE_TAB),
			luabind::value("SPACE", SDL_SCANCODE_SPACE),
			luabind::value("MINUS", SDL_SCANCODE_MINUS),
			luabind::value("EQUALS", SDL_SCANCODE_EQUALS),
			luabind::value("LEFTBRACKET", SDL_SCANCODE_LEFTBRACKET),
			luabind::value("RIGHTBRACKET", SDL_SCANCODE_RIGHTBRACKET),
			luabind::value("BACKSLASH", SDL_SCANCODE_BACKSLASH),
			luabind::value("NONUSHASH", SDL_SCANCODE_NONUSHASH),
			luabind::value("SEMICOLON", SDL_SCANCODE_SEMICOLON),
			luabind::value("APOSTROPHE", SDL_SCANCODE_APOSTROPHE),
			luabind::value("GRAVE", SDL_SCANCODE_GRAVE),
			luabind::value("COMMA", SDL_SCANCODE_COMMA),
			luabind::value("PERIOD", SDL_SCANCODE_PERIOD),
			luabind::value("SLASH", SDL_SCANCODE_SLASH),
			luabind::value("CAPSLOCK", SDL_SCANCODE_CAPSLOCK),
			luabind::value("F1", SDL_SCANCODE_F1),
			luabind::value("F2", SDL_SCANCODE_F2),
			luabind::value("F3", SDL_SCANCODE_F3),
			luabind::value("F4", SDL_SCANCODE_F4),
			luabind::value("F5", SDL_SCANCODE_F5),
			luabind::value("F6", SDL_SCANCODE_F6),
			luabind::value("F7", SDL_SCANCODE_F7),
			luabind::value("F8", SDL_SCANCODE_F8),
			luabind::value("F9", SDL_SCANCODE_F9),
			luabind::value("F10", SDL_SCANCODE_F10),
			luabind::value("F11", SDL_SCANCODE_F11),
			luabind::value("F12", SDL_SCANCODE_F12),
			luabind::value("PRINTSCREEN", SDL_SCANCODE_PRINTSCREEN),
			luabind::value("SCROLLLOCK", SDL_SCANCODE_SCROLLLOCK),
			luabind::value("PAUSE", SDL_SCANCODE_PAUSE),
			luabind::value("INSERT", SDL_SCANCODE_INSERT),
			luabind::value("HOME", SDL_SCANCODE_HOME),
			luabind::value("PAGEUP", SDL_SCANCODE_PAGEUP),
			luabind::value("DELETE", SDL_SCANCODE_DELETE),
			luabind::value("END", SDL_SCANCODE_END),
			luabind::value("PAGEDOWN", SDL_SCANCODE_PAGEDOWN),
			luabind::value("RIGHT", SDL_SCANCODE_RIGHT),
			luabind::value("LEFT", SDL_SCANCODE_LEFT),
			luabind::value("DOWN", SDL_SCANCODE_DOWN),
			luabind::value("UP", SDL_SCANCODE_UP),
			luabind::value("NUMLOCKCLEAR", SDL_SCANCODE_NUMLOCKCLEAR),
			luabind::value("KP_DIVIDE", SDL_SCANCODE_KP_DIVIDE),
			luabind::value("KP_MULTIPLY", SDL_SCANCODE_KP_MULTIPLY),
			luabind::value("KP_MINUS", SDL_SCANCODE_KP_MINUS),
			luabind::value("KP_PLUS", SDL_SCANCODE_KP_PLUS),
			luabind::value("KP_ENTER", SDL_SCANCODE_KP_ENTER),
			luabind::value("KP_1", SDL_SCANCODE_KP_1),
			luabind::value("KP_2", SDL_SCANCODE_KP_2),
			luabind::value("KP_3", SDL_SCANCODE_KP_3),
			luabind::value("KP_4", SDL_SCANCODE_KP_4),
			luabind::value("KP_5", SDL_SCANCODE_KP_5),
			luabind::value("KP_6", SDL_SCANCODE_KP_6),
			luabind::value("KP_7", SDL_SCANCODE_KP_7),
			luabind::value("KP_8", SDL_SCANCODE_KP_8),
			luabind::value("KP_9", SDL_SCANCODE_KP_9),
			luabind::value("KP_0", SDL_SCANCODE_KP_0),
			luabind::value("KP_PERIOD", SDL_SCANCODE_KP_PERIOD),
			luabind::value("NONUSBACKSLASH", SDL_SCANCODE_NONUSBACKSLASH),
			luabind::value("APPLICATION", SDL_SCANCODE_APPLICATION),
			luabind::value("POWER", SDL_SCANCODE_POWER),
			luabind::value("KP_EQUALS", SDL_SCANCODE_KP_EQUALS),
			luabind::value("F13", SDL_SCANCODE_F13),
			luabind::value("F14", SDL_SCANCODE_F14),
			luabind::value("F15", SDL_SCANCODE_F15),
			luabind::value("F16", SDL_SCANCODE_F16),
			luabind::value("F17", SDL_SCANCODE_F17),
			luabind::value("F18", SDL_SCANCODE_F18),
			luabind::value("F19", SDL_SCANCODE_F19),
			luabind::value("F20", SDL_SCANCODE_F20),
			luabind::value("F21", SDL_SCANCODE_F21),
			luabind::value("F22", SDL_SCANCODE_F22),
			luabind::value("F23", SDL_SCANCODE_F23),
			luabind::value("F24", SDL_SCANCODE_F24),
			luabind::value("EXECUTE", SDL_SCANCODE_EXECUTE),
			luabind::value("HELP", SDL_SCANCODE_HELP),
			luabind::value("MENU", SDL_SCANCODE_MENU),
			luabind::value("SELECT", SDL_SCANCODE_SELECT),
			luabind::value("STOP", SDL_SCANCODE_STOP),
			luabind::value("AGAIN", SDL_SCANCODE_AGAIN),
			luabind::value("UNDO", SDL_SCANCODE_UNDO),
			luabind::value("CUT", SDL_SCANCODE_CUT),
			luabind::value("COPY", SDL_SCANCODE_COPY),
			luabind::value("PASTE", SDL_SCANCODE_PASTE),
			luabind::value("FIND", SDL_SCANCODE_FIND),
			luabind::value("MUTE", SDL_SCANCODE_MUTE),
			luabind::value("VOLUMEUP", SDL_SCANCODE_VOLUMEUP),
			luabind::value("VOLUMEDOWN", SDL_SCANCODE_VOLUMEDOWN),
			luabind::value("KP_COMMA", SDL_SCANCODE_KP_COMMA),
			luabind::value("KP_EQUALSAS400", SDL_SCANCODE_KP_EQUALSAS400),
			luabind::value("INTERNATIONAL1", SDL_SCANCODE_INTERNATIONAL1),
			luabind::value("INTERNATIONAL2", SDL_SCANCODE_INTERNATIONAL2),
			luabind::value("INTERNATIONAL3", SDL_SCANCODE_INTERNATIONAL3),
			luabind::value("INTERNATIONAL4", SDL_SCANCODE_INTERNATIONAL4),
			luabind::value("INTERNATIONAL5", SDL_SCANCODE_INTERNATIONAL5),
			luabind::value("INTERNATIONAL6", SDL_SCANCODE_INTERNATIONAL6),
			luabind::value("INTERNATIONAL7", SDL_SCANCODE_INTERNATIONAL7),
			luabind::value("INTERNATIONAL8", SDL_SCANCODE_INTERNATIONAL8),
			luabind::value("INTERNATIONAL9", SDL_SCANCODE_INTERNATIONAL9),
			luabind::value("LANG1", SDL_SCANCODE_LANG1),
			luabind::value("LANG2", SDL_SCANCODE_LANG2),
			luabind::value("LANG3", SDL_SCANCODE_LANG3),
			luabind::value("LANG4", SDL_SCANCODE_LANG4),
			luabind::value("LANG5", SDL_SCANCODE_LANG5),
			luabind::value("LANG6", SDL_SCANCODE_LANG6),
			luabind::value("LANG7", SDL_SCANCODE_LANG7),
			luabind::value("LANG8", SDL_SCANCODE_LANG8),
			luabind::value("LANG9", SDL_SCANCODE_LANG9),
			luabind::value("ALTERASE", SDL_SCANCODE_ALTERASE),
			luabind::value("SYSREQ", SDL_SCANCODE_SYSREQ),
			luabind::value("CANCEL", SDL_SCANCODE_CANCEL),
			luabind::value("CLEAR", SDL_SCANCODE_CLEAR),
			luabind::value("PRIOR", SDL_SCANCODE_PRIOR),
			luabind::value("RETURN2", SDL_SCANCODE_RETURN2),
			luabind::value("SEPARATOR", SDL_SCANCODE_SEPARATOR),
			luabind::value("OUT", SDL_SCANCODE_OUT),
			luabind::value("OPER", SDL_SCANCODE_OPER),
			luabind::value("CLEARAGAIN", SDL_SCANCODE_CLEARAGAIN),
			luabind::value("CRSEL", SDL_SCANCODE_CRSEL),
			luabind::value("EXSEL", SDL_SCANCODE_EXSEL),
			luabind::value("KP_00", SDL_SCANCODE_KP_00),
			luabind::value("KP_000", SDL_SCANCODE_KP_000),
			luabind::value("THOUSANDSSEPARATOR", SDL_SCANCODE_THOUSANDSSEPARATOR),
			luabind::value("DECIMALSEPARATOR", SDL_SCANCODE_DECIMALSEPARATOR),
			luabind::value("CURRENCYUNIT", SDL_SCANCODE_CURRENCYUNIT),
			luabind::value("CURRENCYSUBUNIT", SDL_SCANCODE_CURRENCYSUBUNIT),
			luabind::value("KP_LEFTPAREN", SDL_SCANCODE_KP_LEFTPAREN),
			luabind::value("KP_RIGHTPAREN", SDL_SCANCODE_KP_RIGHTPAREN),
			luabind::value("KP_LEFTBRACE", SDL_SCANCODE_KP_LEFTBRACE),
			luabind::value("KP_RIGHTBRACE", SDL_SCANCODE_KP_RIGHTBRACE),
			luabind::value("KP_TAB", SDL_SCANCODE_KP_TAB),
			luabind::value("KP_BACKSPACE", SDL_SCANCODE_KP_BACKSPACE),
			luabind::value("KP_A", SDL_SCANCODE_KP_A),
			luabind::value("KP_B", SDL_SCANCODE_KP_B),
			luabind::value("KP_C", SDL_SCANCODE_KP_C),
			luabind::value("KP_D", SDL_SCANCODE_KP_D),
			luabind::value("KP_E", SDL_SCANCODE_KP_E),
			luabind::value("KP_F", SDL_SCANCODE_KP_F),
			luabind::value("KP_XOR", SDL_SCANCODE_KP_XOR),
			luabind::value("KP_POWER", SDL_SCANCODE_KP_POWER),
			luabind::value("KP_PERCENT", SDL_SCANCODE_KP_PERCENT),
			luabind::value("KP_LESS", SDL_SCANCODE_KP_LESS),
			luabind::value("KP_GREATER", SDL_SCANCODE_KP_GREATER),
			luabind::value("KP_AMPERSAND", SDL_SCANCODE_KP_AMPERSAND),
			luabind::value("KP_DBLAMPERSAND", SDL_SCANCODE_KP_DBLAMPERSAND),
			luabind::value("KP_VERTICALBAR", SDL_SCANCODE_KP_VERTICALBAR),
			luabind::value("KP_DBLVERTICALBAR", SDL_SCANCODE_KP_DBLVERTICALBAR),
			luabind::value("KP_COLON", SDL_SCANCODE_KP_COLON),
			luabind::value("KP_HASH", SDL_SCANCODE_KP_HASH),
			luabind::value("KP_SPACE", SDL_SCANCODE_KP_SPACE),
			luabind::value("KP_AT", SDL_SCANCODE_KP_AT),
			luabind::value("KP_EXCLAM", SDL_SCANCODE_KP_EXCLAM),
			luabind::value("KP_MEMSTORE", SDL_SCANCODE_KP_MEMSTORE),
			luabind::value("KP_MEMRECALL", SDL_SCANCODE_KP_MEMRECALL),
			luabind::value("KP_MEMCLEAR", SDL_SCANCODE_KP_MEMCLEAR),
			luabind::value("KP_MEMADD", SDL_SCANCODE_KP_MEMADD),
			luabind::value("KP_MEMSUBTRACT", SDL_SCANCODE_KP_MEMSUBTRACT),
			luabind::value("KP_MEMMULTIPLY", SDL_SCANCODE_KP_MEMMULTIPLY),
			luabind::value("KP_MEMDIVIDE", SDL_SCANCODE_KP_MEMDIVIDE),
			luabind::value("KP_PLUSMINUS", SDL_SCANCODE_KP_PLUSMINUS),
			luabind::value("KP_CLEAR", SDL_SCANCODE_KP_CLEAR),
			luabind::value("KP_CLEARENTRY", SDL_SCANCODE_KP_CLEARENTRY),
			luabind::value("KP_BINARY", SDL_SCANCODE_KP_BINARY),
			luabind::value("KP_OCTAL", SDL_SCANCODE_KP_OCTAL),
			luabind::value("KP_DECIMAL", SDL_SCANCODE_KP_DECIMAL),
			luabind::value("KP_HEXADECIMAL", SDL_SCANCODE_KP_HEXADECIMAL),
			luabind::value("LCTRL", SDL_SCANCODE_LCTRL),
			luabind::value("LSHIFT", SDL_SCANCODE_LSHIFT),
			luabind::value("LALT", SDL_SCANCODE_LALT),
			luabind::value("LGUI", SDL_SCANCODE_LGUI),
			luabind::value("RCTRL", SDL_SCANCODE_RCTRL),
			luabind::value("RSHIFT", SDL_SCANCODE_RSHIFT),
			luabind::value("RALT", SDL_SCANCODE_RALT),
			luabind::value("RGUI", SDL_SCANCODE_RGUI),
			luabind::value("MODE", SDL_SCANCODE_MODE),
			luabind::value("AUDIONEXT", SDL_SCANCODE_AUDIONEXT),
			luabind::value("AUDIOPREV", SDL_SCANCODE_AUDIOPREV),
			luabind::value("AUDIOSTOP", SDL_SCANCODE_AUDIOSTOP),
			luabind::value("AUDIOPLAY", SDL_SCANCODE_AUDIOPLAY),
			luabind::value("AUDIOMUTE", SDL_SCANCODE_AUDIOMUTE),
			luabind::value("MEDIASELECT", SDL_SCANCODE_MEDIASELECT),
			luabind::value("WWW", SDL_SCANCODE_WWW),
			luabind::value("MAIL", SDL_SCANCODE_MAIL),
			luabind::value("CALCULATOR", SDL_SCANCODE_CALCULATOR),
			luabind::value("COMPUTER", SDL_SCANCODE_COMPUTER),
			luabind::value("AC_SEARCH", SDL_SCANCODE_AC_SEARCH),
			luabind::value("AC_HOME", SDL_SCANCODE_AC_HOME),
			luabind::value("AC_BACK", SDL_SCANCODE_AC_BACK),
			luabind::value("AC_FORWARD", SDL_SCANCODE_AC_FORWARD),
			luabind::value("AC_STOP", SDL_SCANCODE_AC_STOP),
			luabind::value("AC_REFRESH", SDL_SCANCODE_AC_REFRESH),
			luabind::value("AC_BOOKMARKS", SDL_SCANCODE_AC_BOOKMARKS),
			luabind::value("BRIGHTNESSDOWN", SDL_SCANCODE_BRIGHTNESSDOWN),
			luabind::value("BRIGHTNESSUP", SDL_SCANCODE_BRIGHTNESSUP),
			luabind::value("DISPLAYSWITCH", SDL_SCANCODE_DISPLAYSWITCH),
			luabind::value("KBDILLUMTOGGLE", SDL_SCANCODE_KBDILLUMTOGGLE),
			luabind::value("KBDILLUMDOWN", SDL_SCANCODE_KBDILLUMDOWN),
			luabind::value("KBDILLUMUP", SDL_SCANCODE_KBDILLUMUP),
			luabind::value("EJECT", SDL_SCANCODE_EJECT),
			luabind::value("SLEEP", SDL_SCANCODE_SLEEP),
			luabind::value("APP1", SDL_SCANCODE_APP1),
			luabind::value("APP2", SDL_SCANCODE_APP2),
			luabind::value("AUDIOREWIND", SDL_SCANCODE_AUDIOREWIND),
			luabind::value("AUDIOFASTFORWARD", SDL_SCANCODE_AUDIOFASTFORWARD),
			luabind::value("NUM_SCANCODES", SDL_NUM_SCANCODES)
		];
	}

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	LuaBindingRegisterFunctionDefinitionForType(InputLuaBindings, SDL_GameControllerButton) {
		return luabind::class_<gamepad_buttons>("GamepadButton")

		.enum_("GamepadButton")[
			luabind::value("INVALID", SDL_CONTROLLER_BUTTON_INVALID),
			luabind::value("A", SDL_CONTROLLER_BUTTON_A),
			luabind::value("B", SDL_CONTROLLER_BUTTON_B),
			luabind::value("X", SDL_CONTROLLER_BUTTON_X),
			luabind::value("Y", SDL_CONTROLLER_BUTTON_Y),
			luabind::value("BACK", SDL_CONTROLLER_BUTTON_BACK),
			luabind::value("GUIDE", SDL_CONTROLLER_BUTTON_GUIDE),
			luabind::value("START", SDL_CONTROLLER_BUTTON_START),
			luabind::value("LEFTSTICK", SDL_CONTROLLER_BUTTON_LEFTSTICK),
			luabind::value("RIGHTSTICK", SDL_CONTROLLER_BUTTON_RIGHTSTICK),
			luabind::value("LEFTSHOULDER", SDL_CONTROLLER_BUTTON_LEFTSHOULDER),
			luabind::value("RIGHTSHOULDER", SDL_CONTROLLER_BUTTON_RIGHTSHOULDER),
			luabind::value("DPAD_UP", SDL_CONTROLLER_BUTTON_DPAD_UP),
			luabind::value("DPAD_DOWN", SDL_CONTROLLER_BUTTON_DPAD_DOWN),
			luabind::value("DPAD_LEFT", SDL_CONTROLLER_BUTTON_DPAD_LEFT),
			luabind::value("DPAD_RIGHT", SDL_CONTROLLER_BUTTON_DPAD_RIGHT),
			luabind::value("MAX", SDL_CONTROLLER_BUTTON_MAX)
		];
	}

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	LuaBindingRegisterFunctionDefinitionForType(InputLuaBindings, SDL_GameControllerAxis) {
		return luabind::class_<gamepad_axis>("GamepadAxis")

		.enum_("GamepadAxis")[
			luabind::value("INVALID", SDL_CONTROLLER_AXIS_INVALID),
			luabind::value("LEFTX", SDL_CONTROLLER_AXIS_LEFTX),
			luabind::value("LEFTY", SDL_CONTROLLER_AXIS_LEFTY),
			luabind::value("RIGHTX", SDL_CONTROLLER_AXIS_RIGHTX),
			luabind::value("RIGHTY", SDL_CONTROLLER_AXIS_RIGHTY),
			luabind::value("TRIGGERLEFT", SDL_CONTROLLER_AXIS_TRIGGERLEFT),
			luabind::value("TRIGGERRIGHT", SDL_CONTROLLER_AXIS_TRIGGERRIGHT),
			luabind::value("MAX", SDL_CONTROLLER_AXIS_MAX)
		];
	}
}